---

- fail:
    msg: "Target env name '{{ env }}' not present in variables"
  when: env not in environments

- debug:
    msg: "Switching to environment name '{{ env }}'"

- include: "proxy/proxy.yml"
  when: "'proxy' in environments[env]"

- include: "dns/dns.yml"
  when: "'dns' in environments[env]"
