---
# handlers file for ansible-role-workstation-env-switcher
- name: restart docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
