- debug:
    msg: "Configure proxy"

- when: environments[env]["proxy"]["enabled"]
  include: "enable/{{ item }}.yml"
  loop: "{{ environments[env]['proxy']['services'] }}"

- when: not environments[env]["proxy"]["enabled"]
  include: "disable/{{ item }}.yml"
  loop: "{{ environments[env]['proxy']['services'] }}"
